name: Unittests
on:
  push:
    branches:
      - master
jobs:
  unittests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm -i
      - name: Run unittests
        run: |
          make test